development:
  secret_key_base: 0a9b9fa4dbd2ffb6d8bedefbc17bafb4d69071083c021e320c82e42a3f3b74afe4770c5ad0600c0bee8701020e597973ac00cfc0d1366eab2e865e0ecfd1c4a1
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: b4c0ffacfa7730372a905a94e988d4bbade8057be9db2c9b8f5e91a1b6db82f4bbdffdda9480420d8d29c216fccc0564bdf1cce4ad2f2553e9f73e065982bc08

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>